#ifndef CERT_H

#define CERT_H
const char* rootCACertificate = 
"-----BEGIN CERTIFICATE-----\n"
"MIIDtTCCAp0CFChoIq/xlHIPz5SDRgQGIfc0/xN+MA0GCSqGSIb3DQEBCwUAMIGW\n"
"MQswCQYDVQQGEwJQSzEMMAoGA1UECAwDS1BLMREwDwYDVQQHDAhQZXNoYXdhcjEm\n"
"MCQGA1UECgwdR3JlZW4gd2VuZCBlbmVyZ3kgcHZ0IGxpbWl0ZWQxDDAKBgNVBAsM\n"
"A3ImZDENMAsGA1UEAwwEc2FhZDEhMB8GCSqGSIb3DQEJARYSc2FhZC5nd2VAZ21h\n"
"aWwuY29tMB4XDTIzMDkyMjA1NDExOFoXDTMwMDkyMDA1NDExOFowgZYxCzAJBgNV\n"
"BAYTAlBLMQwwCgYDVQQIDANLUEsxETAPBgNVBAcMCFBlc2hhd2FyMSYwJAYDVQQK\n"
"DB1HcmVlbiB3ZW5kIGVuZXJneSBwdnQgbGltaXRlZDEMMAoGA1UECwwDciZkMQ0w\n"
"CwYDVQQDDARzYWFkMSEwHwYJKoZIhvcNAQkBFhJzYWFkLmd3ZUBnbWFpbC5jb20w\n"
"ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCrdUcQtCFV1YgP47SwZ/zo\n"
"/b7PYTZHTVW2CPi2UgCtvR2DnSBUnmGD81py/Oj2y/6yvUx0rt+9LKqeNSMmDdqf\n"
"b2w5OdTxIaXbN09x/90UnfhsK1BUIO+0nhg8AtuWZJwolSvIVixTDTuplS3QIEr4\n"
"VkgUi55+kG3QoX05rm/zrfoWRFr8g/Tkpupvf9f4Vb/wXbwzKZNBIOR7AuRu9PAi\n"
"UDKuY3hN5doQALhrAr82dcuQFAw8WvMFdEWWpeqOzbRqoNiHYWbP+wJygpDzivE4\n"
"pAH/wqknIeU3SzXkdMZkU0tuDs1+/ndB1tJ2w9/jvgR+GcyDHDXQaIOYZwi4+Jx5\n"
"AgMBAAEwDQYJKoZIhvcNAQELBQADggEBABsPl15WB+qSskBg6Vufg1N0FXaC+AG7\n"
"CjdUcZUIF6l5cH3uALm2BnyhKTlcX+uNPsN0LY2hQzrmHYzrSTb4CwaH0lBTmNoB\n"
"nCiEaNsPYrBsuSVVMolrUxA2yLd4RJi+FhaidiGtLY5c+zvrzWzRbFE2xrmhlYpA\n"
"joldY6DWrjbJMhBi3aGik/qgOXCC5xEMQhMOM9te8TSFwa0/Y07DQSnWCZGJI5KC\n"
"0AQo04OzLL6NLvxfUj7jvsMupGc5qSAZk2MoSKGHV6dujv+xJnABxfcMChFs/ewB\n"
"A/aRZzyLVXXM5AI4Tsjb4b7iuGdBzOKX/I9lChu6IaKv6agSCnJXmV4=\n"
"-----END CERTIFICATE-----\n";


#endif
